# Generated by Django 4.1.7 on 2023-03-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lat', models.FloatField(default='0.0')),
                ('Lng', models.FloatField(default='0.0')),
                ('Image', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
