# Generated by Django 4.1.7 on 2023-03-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbage',
            name='image',
            field=models.ImageField(default='img/none_image.png', upload_to='img/'),
        ),
    ]
