# Generated by Django 4.1.7 on 2023-03-03 00:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_garbage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('garbage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.garbage')),
            ],
        ),
    ]
